### ISSUE TITLE
can't add a new key into hash during iteration (RuntimeError) が出て起動しない場合がある

### ISSUE THREAD

**Issue by krororo** [tmtm/parallel_server#4]
以下のようなエラーが発生して起動しない場合があります。

```
.../gems/ruby/2.6.0/gems/parallel_server-0.1.6.1/lib/parallel_server/prefork.rb:327:in `start_child': can't add a new key into hash during iteration (RuntimeError)
    from .../gems/ruby/2.6.0/gems/parallel_server-0.1.6.1/lib/parallel_server/prefork.rb:262:in `block in adjust_children'
    from .../gems/ruby/2.6.0/gems/parallel_server-0.1.6.1/lib/parallel_server/prefork.rb:261:in `times'
    from .../gems/ruby/2.6.0/gems/parallel_server-0.1.6.1/lib/parallel_server/prefork.rb:261:in `adjust_children'
    from .../gems/ruby/2.6.0/gems/parallel_server-0.1.6.1/lib/parallel_server/prefork.rb:70:in `start'
    from ...
```

環境は以下のような感じです。
* ruby: 2.6.3
* parallel_server: 0.1.6.1

**Comment by krororo** [comment]
すみません。使い方の問題な可能性が高そうということが分かったので一旦クローズします。
